name: DevOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2 Kubernetes
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/devops-virtual-lab
          git pull origin main
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml
